# Generated by Django 2.2.7 on 2019-11-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20191121_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
